In [3]:
import os 
import tensorflow as tf
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [46]:
tf.config.list_physical_devices("GPU")

[]

# Initialization of tensors

In [18]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
x = tf.constant([[1, 2, 3], [3, 2, 1]])

print(x)

tf.Tensor(
[[1 2 3]
 [3 2 1]], shape=(2, 3), dtype=int32)


In [19]:
x = tf.ones(shape=(3, 3))
y = tf.zeros(shape=(3, 3))
z = tf.eye(3)

print(x, y, z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [22]:
x = tf.random.normal((3, 3, 120), 0.0, 1.0)
# uniform and so on... 

print(x)

tf.Tensor(
[[[-0.4564397   0.79123414  0.6846837  ...  0.02874592 -2.120488
   -0.15572165]
  [ 1.0148517  -0.93393373 -0.6623417  ...  0.57379705 -1.6374512
   -0.7660145 ]
  [ 0.84173054  1.8689947  -1.4755107  ... -0.18964076 -2.493348
   -1.0767388 ]]

 [[ 1.073923   -1.4254358   1.1261417  ... -0.6888673   0.8691251
    0.9743533 ]
  [-0.17090046 -1.2887611   0.6528417  ...  0.67333233  0.20509249
    1.2391102 ]
  [-0.7499105   2.1344068   0.14321797 ...  0.04151248  0.00260847
   -0.9967259 ]]

 [[-1.7321798   0.33279347 -0.6323542  ...  0.15890996  0.37785167
    0.7369419 ]
  [-0.81759465 -0.4324227  -0.34052217 ... -0.21434939  0.4677558
   -0.7622966 ]
  [ 0.15390982 -1.121995   -0.02544445 ...  0.1239057  -1.1996593
    0.13470636]]], shape=(3, 3, 120), dtype=float32)


In [23]:
x = tf.range(start=1, limit=10, delta=2)

print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


## Types custing

In [24]:
x = tf.cast(x, dtype=tf.float32)
# tf.float16 32 64
# tf.int8 16 32 64
# tf.bool

# Math

In [26]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y # eq

print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [27]:
z = tf.subtract(x, y)
z = x - y # eq

print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [41]:
z = tf.divide(x, y)
z = x / y # eq

z = tf.multiply(x, y)
z = x * y # eq

In [42]:
z = x ** 5

print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


## Linear algebra

In [40]:
z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x * y, axis=0) # eq

print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [43]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z = tf.matmul(x, y)
z = x @ y # eq

print(z)

tf.Tensor(
[[ 1.4752306   0.08697622  1.084508    1.1688131 ]
 [ 0.31730014 -0.5834547   2.0274515   2.6623907 ]], shape=(2, 4), dtype=float32)


# Indexing 

In [52]:
x = tf.constant([0, 1, 1, 1, 2, 2, 3, 3, 3])

# similarly like np arrays
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])

tf.Tensor([0 1 1 1 2 2 3 3 3], shape=(9,), dtype=int32)
tf.Tensor([1 1 1 2 2 3 3 3], shape=(8,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 2 3 3], shape=(5,), dtype=int32)


In [53]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)

print(x_ind)

tf.Tensor([0 1], shape=(2,), dtype=int32)


In [55]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# separating dimentions by comma 
print(x[0, :])


tf.Tensor([1 2], shape=(2,), dtype=int32)


# Reshaping

In [59]:
x = tf.range(9)
print(x)

print()

x = tf.reshape(x, shape=(3, 3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [61]:
x = tf.transpose(x, perm=[1, 0]) # permutation 
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
